//  HomeCoordinator.swift
//  NetworkImpl
//
//  Created by Huy Trinh Duc on 17/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import Foundation
import XCoordinator
import UIKit
import BaseCore

enum HomeRoute: Route {
    case home
}

class HomeCoordinator: NavigationCoordinator<HomeRoute> {
    
    //Init bình thường
    init() {
        super.init(initialRoute: .home)
    }
    
    //MARK: Tách coordinator ra từ thằng cha thì dùng hàm này
//    init(rootViewController: UINavigationController) {
//        super.init(rootViewController: rootViewController, initialRoute: nil)
//        trigger(.demo)
    
//        Note: bên ParentRoute khi switch đến case cần tách ở child thì gọi:
//        addChild(ChildCoordinator.init(rootViewController: rootViewController))
//        return .none()
//    }

    override func prepareTransition(for route: HomeRoute) -> NavigationTransition {
        switch route {
        case .home:
//            let vc = HomeViewController()
//            let vm = HomeViewModel(router: unownedRouter)
//            vc.bind(to: vm)
            return .none()
        }
    }
    
}
