//  HomeViewModel.swift
//  NetworkImpl
//
//  Created by Huy Trinh Duc on 17/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import Foundation
import RxSwift
import RxCocoa
import XCoordinator
import UIKit
import BaseCore

class HomeViewModel: EducaViewModel {
    
    struct Input {
        
    }
    
    struct Output {
        
    }
    
    private let router: UnownedRouter<LoginRoute>
    private let bag = DisposeBag()
    
    init(router: UnownedRouter<LoginRoute>) {
        self.router = router
    }
    
    func transform(input: Input) -> Output {
        return Output()
    }
}
