//  LoginCoordinator.swift
//  NetworkImpl
//
//  Created by Huy Trinh Duc on 17/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import Foundation
import XCoordinator
import UIKit
import BaseCore

enum LoginRoute: Route {
    case login
    case home
}

class LoginCoordinator: NavigationCoordinator<LoginRoute> {
    
    //Init bình thường
    init() {
        super.init(initialRoute: .login)
    }

    override func prepareTransition(for route: LoginRoute) -> NavigationTransition {
        switch route {
        case .login:
            let vc = LoginViewController()
            let uc = DummyRepository().makeDummyUseCase()
            let vm = LoginViewModel(router: unownedRouter, useCase: uc)
            vc.bind(to: vm)
            return .push(vc)
        case .home:
            let vc = HomeViewController()
            let vm = HomeViewModel(router: unownedRouter)
            vc.bind(to: vm)
            return .set([vc])
        }
    }
    
}
