//  APIError.swift
//  BaseCoreImpl
//
//  Created by Huy Trinh Duc on 16/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import Foundation

public enum APIError: Error {
    case error(code: Int, message: String)
    case invalidResponseData(data: Any)
    case unknown
    
    public var displayText: String {
        switch self {
        case .invalidResponseData:
            return "Invalid response"
        case .error(_, let message):
            //switch errorResponseCode
            return message
        case .unknown:
            return "Unknown error"
        }
    }
    
    public var code: Int {
        switch self {
        case .error(let code, _):
            return code
        default :
            return 0
        }
    }
}
