//  AuthenticateUseCase.swift
//  NetworkImpl
//
//  Created by Huy Trinh Duc on 17/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import Foundation
import RxSwift

protocol AuthenticateUseCaseType {
    func login(userName: String, passWord: String) -> Observable<UserModel>
}

struct AuthenticateUseCase: AuthenticateUseCaseType {
    
    private let repository: AuthenticateRepository
    
    init(repository: AuthenticateRepository) {
        self.repository = repository
    }

    func login(userName: String, passWord: String) -> Observable<UserModel> {
        let param = [
            "userName": userName,
            "password": passWord
        ]
        return repository.login(param)
    }
    
}
