//  AuthenticateAPIRouter.swift
//  NetworkImpl
//
//  Created by Huy Trinh Duc on 17/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import UIKit
import Alamofire

enum AuthenticateAPIRouter: APIInputBase {
    
    var headers: HTTPHeaders? {
        if requireToken {
            var header = HTTPHeaders()
            header.add(.authorization(UserUtils.getAccessToken()))
            return header
        }
        else {
            return nil
        }
    }
    
    var url: URL {
        let testBaseURL = URL.init(string: "http://teacher.edupiatutor.com.vn")!
//        return Config.baseURL.appendingPathComponent(path)
        return testBaseURL.appendingPathComponent(path)
    }
    
    var method: HTTPMethod {
        switch self {
        case .login:
            return .post
        }
    }
    
    var encoding: ParameterEncoding {
        return method == .get ? URLEncoding.default : JSONEncoding.default
    }
    
    
    var parameters: [String : Any]? {
        switch self {
        case .login(let param):
            return param
        }
    }
    
    var path: String {
        switch self {
        case .login:
            return "/api/teacher/auth/login"
        }
    }
    
    var requireToken: Bool {
        switch self {
        case .login:
            return false
        }
    }
    
    case login(_ param: [String: Any])
}
