//  DummyAPIRouter.swift
//  NetworkImpl
//
//  Created by Huy Trinh Duc on 18/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import UIKit
import Alamofire

enum DummyAPIRouter: APIInputBase {
    
    var headers: HTTPHeaders? {
        if requireToken {
            var header = HTTPHeaders()
            header.add(.authorization(UserUtils.getAccessToken()))
            return header
        }
        else {
            return nil
        }
    }
    
    var url: URL {
        return URL.init(string: "https://jsonplaceholder.typicode.com/todos/")!.appendingPathComponent(path)
//        return Config.baseURL.appendingPathComponent(path)
    }
    
    var method: HTTPMethod {
        switch self {
        case .apidemo:
            return .get
        }
    }
    
    var encoding: ParameterEncoding {
        return method == .get ? URLEncoding.default : JSONEncoding.default
    }
    
    
    var parameters: [String : Any]? {
        switch self {
        case .apidemo:
            return nil
        }
    }
    
    var path: String {
        switch self {
        case .apidemo:
            return "1"
        }
    }
    
    var requireToken: Bool {
        switch self {
        case .apidemo:
            return false
        }
    }
    
    case apidemo
}
