//  AuthenticateRepository.swift
//  NetworkImpl
//
//  Created by Huy Trinh Duc on 17/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import Foundation
import RxSwift
import BaseCore

import RxCocoa

protocol AuthenticateRepositoryType {
    func login(_ param: [String: Any]) -> Observable<UserModel>
}

struct AuthenticateRepository: AuthenticateRepositoryType {

    func login(_ param: [String: Any]) -> Observable<UserModel> {
        return APIService
            .shared
            .request(nonBaseResponse: AuthenticateAPIRouter.login(param))
            .asObservable()
            .observe(on: MainScheduler.asyncInstance)
            .handleError1()
            .share()
    }
    
}
