//  DummyRepository.swift
//  NetworkImpl
//
//  Created by Huy Trinh Duc on 18/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import Foundation
import Foundation
import RxSwift
import BaseCore

protocol DummyRepositoryType {
    func getDummy() -> Observable<DummyModel>
}

struct DummyRepository: DummyRepositoryType {

    func getDummy() -> Observable<DummyModel> {
        return APIService
            .shared
            .request(nonBaseResponse: DummyAPIRouter.apidemo)
            .asObservable()
            .observe(on: MainScheduler.asyncInstance)
            .handleError()
            .share()
    }
    
}
